litellm_settings:
  drop_params: true

model_list:
  - model_name: claude-sonnet-5
    litellm_params:
      model: github_copilot/claude-sonnet-5

  - model_name: claude-opus-5
    litellm_params:
      model: github_copilot/claude-opus-5

  - model_name: gpt-6-astra
    model_info:
      mode: responses
    litellm_params:
      model: chatgpt/gpt-6-astra
