! ------------------------------------------------------------------------------
! ROFI Color theme
! User: Robot
! Copyright: Rasmus Steinke
! ------------------------------------------------------------------------------
rofi.color-enabled: true
rofi.color-window: #1E1E1E, #111111, #111111
rofi.color-normal: #1E1E1E, #A6A6A6 ,#1E1E1E, #181818, #FF0000
rofi.color-active: #1E1E1E, #C6C6B7, #1E1E1E, #181818, #80cbc4
rofi.color-urgent: #273238, #ff1844, #273238, #394249, #ff1844
