#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus        off            \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             on             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.9            \
                window_animation_duration  0.0            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                20             \
                bottom_padding             20             \
                left_padding               20             \
                right_padding              20             \
                window_gap                 10

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Messages|Preview|Spark|Calendar|Finder|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|System Information|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
