    SELECT
    DISTINCT
    WHERE
        AND & OR
        IN
        BETWEEN
        LIKE
        IS NULL / IS NOT NULL
    GROUP BY
     HAVING
     ORDER BY
     AS (alias)
     LIMIT
     CASE
     UNION
     SQL UNION ALL
     INTERSECT
     EXCEPT / MINUS
     INSERT INTO
     SQL ON DUPLICATE KEY UPDATE
     UPDATE
     DELETE
     MERGE
     TRUNCATE TABLE
     CREATE DATABASE
     DROP DATABASE
     CREATE TABLE
     ALTER TABLE
     DROP TABLE
        INNER JOIN
        CROSS JOIN
        LEFT JOIN
        RIGHT JOIN
        FULL JOIN
        SELF JOIN
        NATURAL JOIN
        EXISTS
        ALL
        ANY / SOME
        CREATE INDEX
    EXPLAIN
    OPTIMIZE
